import { Order } from "@/types/order";

export const mockOrders: Order[] = [
  {
    id: "ORD-9385",
    customer: "Sarah Johnson",
    pickupAddress: "123 Market St, San Francisco, CA",
    deliveryAddress: "456 Main St, San Francisco, CA",
    date: "2025-05-29",
    amount: 42.99,
    status: "In Transit",
    items: 3,
    paymentMethod: "Credit Card",
  },
  {
    id: "ORD-9384",
    customer: "Mike Smith",
    pickupAddress: "789 Valencia St, San Francisco, CA",
    deliveryAddress: "101 Broadway, San Francisco, CA",
    date: "2025-05-29",
    amount: 27.50,
    status: "Pending",
    items: 2,
    paymentMethod: "PayPal",
  },
  {
    id: "ORD-9383",
    customer: "Emily Davis",
    pickupAddress: "222 Mission St, San Francisco, CA",
    deliveryAddress: "333 Howard St, San Francisco, CA",
    date: "2025-05-28",
    amount: 56.25,
    status: "Delivered",
    items: 5,
    paymentMethod: "Credit Card",
  },
  {
    id: "ORD-9382",
    customer: "James Wilson",
    pickupAddress: "555 Brannan St, San Francisco, CA",
    deliveryAddress: "777 Harrison St, San Francisco, CA",
    date: "2025-05-28",
    amount: 19.99,
    status: "Delivered",
    items: 1,
    paymentMethod: "Cash on Delivery",
  },
  {
    id: "ORD-9381",
    customer: "Jessica Brown",
    pickupAddress: "888 Folsom St, San Francisco, CA",
    deliveryAddress: "999 Townsend St, San Francisco, CA",
    date: "2025-05-27",
    amount: 84.50,
    status: "Delivered",
    items: 7,
    paymentMethod: "Credit Card",
  }
];